name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Ganti dengan nama branch yang Anda gunakan

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t laravel-app .
        working-directory: ./docker/php  # Sesuaikan dengan lokasi Dockerfile

      - name: Tag the Docker image
        run: docker tag laravel-app ${{ secrets.DOCKER_USERNAME }}/laravel-app:latest

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/laravel-app:latest
